CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	username VARCHAR NOT NULL,
	password VARCHAR NOT NULL,
	name VARCHAR NOT NULL,
	invert BOOLEAN NOT NULL
);

CREATE TABLE articles (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	uid INTEGER NOT NULL,
	datetime DATETIME NOT NULL,
	title VARCHAR,
	content TEXT
);

CREATE TABLE comments (
	id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	aid INTEGER NOT NULL,
	uid INTEGER NOT NULL,
	datetime DATETIME NOT NULL,
	title VARCHAR,
	content TEXT
);
